### ISSUE TITLE
Why did you take out compare and what was wrong with mine?

### ISSUE THREAD

**Issue by runvnc** [flaviut/easy-bcrypt#1]
First of all, what was wrong with my bcrypt?  It seems like you mostly copied it.  Secondly, why did you take the compare function out, which is there to counter the timing attacks you say you are concerned about?   Maybe just put compare and compare_string back in..and then we can remove the bcrypt module from packages.json so I don't have to update it.

**Comment by flaviut** [comment]
First off - I apologize for how I handled my concerns about your bcrypt wrapper. It was completely unprofessional, I should have handled it more politely.

This is not a wrapper around the bcrypt library, it is a wrapper around the [rg3/bcrypt](https://github.com/rg3/bcrypt) wrapper of bcrypt, which provides an easier to understand interface.

Excellent point about constant time string comparison, I'll be sure to add that in soon. The reason I have not done so yet is that while it does create the possibility of an attacker obtaining the hash, that hash cannot be reasonably brute-forced without the salt, which an attacker has no way to obtain.

**Comment by runvnc** [comment]
Ok.. don't know what you mean easier to understand interface.

**Comment by flaviut** [comment]
bcrypt's documentation seems to be non-existent, so I don't know how to use it. rg3 created an interface that he documents well in the header file at https://github.com/rg3/bcrypt/blob/master/bcrypt.h, whose usage I do understand.

**Comment by flaviut** [comment]
Fixed in 668cca03d3475e1db681169becadb43476135e8a
